work_dir: ./ntu60_TransferLearnToPKU/fine_tuned_on_PKU
weights: ./ntu60_TransferLearnToPKU/pretrained_on_NTU/epoch295_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: ./data/pku_part1_frame50/xsub/train_position.npy
  label_path: ./data/pku_part1_frame50/xsub/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: ./data/pku_part1_frame50/xsub/val_position.npy
  label_path: ./data/pku_part1_frame50/xsub/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 51 # the action categories of PKU. Particular action mapping from NTU to PKU will be made at 'feeder.ntu_feeder.Feeder_single#load_data'
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: 0
batch_size: 128
test_batch_size: 128
num_epoch: 100
stream: 'joint'

# log
save_interval: -1
eval_interval: 5
